### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by lishaduck** [ParkerH27/Gpa_Calculator#4]
Now that [PSDTools/GPA_Calculator](https://github.com/PSDTools/GPA_Calculator) exists,
- should this whole repo be
  - archived/
  - moved/
  - deleted?
- And should #3 be moved?
- Or closed due to psdtools/gpa_calculator#25?

**Comment by ParkerH27** [comment]
closed due to ExpUI
I am just going to leave this repo as is for the time being
